// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_dt
Rcpp::NumericVector rcpp_dt(Rcpp::NumericVector x, double nu, double delta);
RcppExport SEXP _boodist_rcpp_dt(SEXP xSEXP, SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_dt(x, nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_pt
Rcpp::NumericVector rcpp_pt(Rcpp::NumericVector q, double nu, double delta, bool lower);
RcppExport SEXP _boodist_rcpp_pt(SEXP qSEXP, SEXP nuSEXP, SEXP deltaSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_pt(q, nu, delta, lower));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_qt
Rcpp::NumericVector rcpp_qt(Rcpp::NumericVector p, double nu, double delta, bool lower);
RcppExport SEXP _boodist_rcpp_qt(SEXP pSEXP, SEXP nuSEXP, SEXP deltaSEXP, SEXP lowerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type lower(lowerSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_qt(p, nu, delta, lower));
    return rcpp_result_gen;
END_RCPP
}
// t_mean
double t_mean(double nu, double delta);
RcppExport SEXP _boodist_t_mean(SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(t_mean(nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// t_variance
double t_variance(double nu, double delta);
RcppExport SEXP _boodist_t_variance(SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(t_variance(nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// t_skewness
double t_skewness(double nu, double delta);
RcppExport SEXP _boodist_t_skewness(SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(t_skewness(nu, delta));
    return rcpp_result_gen;
END_RCPP
}
// t_kurtosis_excess
double t_kurtosis_excess(double nu, double delta);
RcppExport SEXP _boodist_t_kurtosis_excess(SEXP nuSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(t_kurtosis_excess(nu, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_boodist_rcpp_dt", (DL_FUNC) &_boodist_rcpp_dt, 3},
    {"_boodist_rcpp_pt", (DL_FUNC) &_boodist_rcpp_pt, 4},
    {"_boodist_rcpp_qt", (DL_FUNC) &_boodist_rcpp_qt, 4},
    {"_boodist_t_mean", (DL_FUNC) &_boodist_t_mean, 2},
    {"_boodist_t_variance", (DL_FUNC) &_boodist_t_variance, 2},
    {"_boodist_t_skewness", (DL_FUNC) &_boodist_t_skewness, 2},
    {"_boodist_t_kurtosis_excess", (DL_FUNC) &_boodist_t_kurtosis_excess, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_boodist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
