# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dt <- function(x, nu, delta) {
    .Call(`_boodist_rcpp_dt`, x, nu, delta)
}

rcpp_pt <- function(q, nu, delta, lower) {
    .Call(`_boodist_rcpp_pt`, q, nu, delta, lower)
}

rcpp_qt <- function(p, nu, delta, lower) {
    .Call(`_boodist_rcpp_qt`, p, nu, delta, lower)
}

t_mean <- function(nu, delta) {
    .Call(`_boodist_t_mean`, nu, delta)
}

t_variance <- function(nu, delta) {
    .Call(`_boodist_t_variance`, nu, delta)
}

t_skewness <- function(nu, delta) {
    .Call(`_boodist_t_skewness`, nu, delta)
}

t_kurtosis_excess <- function(nu, delta) {
    .Call(`_boodist_t_kurtosis_excess`, nu, delta)
}

