# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_dgumbel <- function(x, a, b, log) {
    .Call(`_boodist_rcpp_dgumbel`, x, a, b, log)
}

rcpp_pgumbel <- function(q, a, b, lower) {
    .Call(`_boodist_rcpp_pgumbel`, q, a, b, lower)
}

rcpp_qgumbel <- function(p, a, b, lower) {
    .Call(`_boodist_rcpp_qgumbel`, p, a, b, lower)
}

gumbel_mean <- function(a, b) {
    .Call(`_boodist_gumbel_mean`, a, b)
}

gumbel_median <- function(a, b) {
    .Call(`_boodist_gumbel_median`, a, b)
}

gumbel_mode <- function(a, b) {
    .Call(`_boodist_gumbel_mode`, a, b)
}

gumbel_sd <- function(a, b) {
    .Call(`_boodist_gumbel_sd`, a, b)
}

gumbel_skewness <- function(a, b) {
    .Call(`_boodist_gumbel_skewness`, a, b)
}

gumbel_kurtosis <- function(a, b) {
    .Call(`_boodist_gumbel_kurtosis`, a, b)
}

gumbel_kurtosis_excess <- function(a, b) {
    .Call(`_boodist_gumbel_kurtosis_excess`, a, b)
}

rcpp_dt <- function(x, nu, delta) {
    .Call(`_boodist_rcpp_dt`, x, nu, delta)
}

rcpp_pt <- function(q, nu, delta, lower) {
    .Call(`_boodist_rcpp_pt`, q, nu, delta, lower)
}

rcpp_qt <- function(p, nu, delta, lower) {
    .Call(`_boodist_rcpp_qt`, p, nu, delta, lower)
}

t_mean <- function(nu, delta) {
    .Call(`_boodist_t_mean`, nu, delta)
}

t_variance <- function(nu, delta) {
    .Call(`_boodist_t_variance`, nu, delta)
}

t_skewness <- function(nu, delta) {
    .Call(`_boodist_t_skewness`, nu, delta)
}

t_kurtosis_excess <- function(nu, delta) {
    .Call(`_boodist_t_kurtosis_excess`, nu, delta)
}

